In [2]:
from __future__ import print_function

from osgeo import gdal

print("GDAL's version is: " + gdal.__version__)

GDAL's version is: 3.6.4


In [12]:
# Open a GDAL dataset
dataset = gdal.Open('LC08_L2SP_114035_20240730_20240801_02_T1_SR_B7.TIF', gdal.GA_ReadOnly)

print(dataset)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7fb1731daca0> >


In [16]:
# How many bands does this image have?
num_bands = dataset.RasterCount
print('Number of bands in image: {n}\n'.format(n=num_bands))

Number of bands in image: 1

Image size is: 7821 rows x 7681 columns

Raster description: LC08_L2SP_114035_20240730_20240801_02_T1_SR_B7.TIF
Raster metadata:
{'AREA_OR_POINT': 'Point'}


Raster driver: GTiff

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7fb171c496b0> >
Band datatype: 2
Band datatype: UInt16
Band datatype size in bytes: 16
Band range: 61629.0 to 6824.0
Band mean, stddev: 12566.175226028, 5918.9236170827



In [17]:
# How many rows and cols?
rows = dataset.RasterYSize
cols = dataset.RasterXSize
print('Image size is: {r} rows x {c} columns\n'.format(r=rows, c=cols))

Image size is: 7821 rows x 7681 columns



In [18]:
# Does the raster have a description or metadata?
desc = dataset.GetDescription()
metadata = dataset.GetMetadata()

print('Raster description: {desc}'.format(desc=desc))
print('Raster metadata:')
print(metadata)
print('\n')

Raster description: LC08_L2SP_114035_20240730_20240801_02_T1_SR_B7.TIF
Raster metadata:
{'AREA_OR_POINT': 'Point'}




In [19]:
# What driver was used to open the raster?
driver = dataset.GetDriver()
print('Raster driver: {d}\n'.format(d=driver.ShortName))

Raster driver: GTiff



In [20]:
# Open the blue band in our image
blue = dataset.GetRasterBand(1)
print(blue)

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7fb171d4f420> >


In [21]:
# What is the band's datatype?
datatype = blue.DataType
print('Band datatype: {dt}'.format(dt=datatype))

Band datatype: 2


In [23]:
# If you recall for our discussion of enumerated types,
# this "3" we printed has a more useful definition for us to use
datatype_name = gdal.GetDataTypeName(datatype)
print('Band datatype: {dt}'.format(dt=datatype_name))

Band datatype: UInt16


In [24]:
# We can also ask how much space does this datatype take up
bytes = gdal.GetDataTypeSize(datatype)
print('Band datatype size in bytes: {b}'.format(b=bytes))

Band datatype size in bytes: 16


In [26]:
# How about some band statistics?
band_max, band_min, band_mean, band_stddev = blue.GetStatistics(0, 1)
print('Band range: {minimum} to {maximum}'.format(minimum=band_min,
                                                  maximum=band_max))
print('Band mean, stddev: {m}, {s}\n'.format(m=band_mean, s=band_stddev))

blue_data = blue.ReadAsArray()
print(blue_data)

Band range: 61629.0 to 6824.0
Band mean, stddev: 12566.175226028, 5918.9236170827

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
import numpy
print(numpy.__version__)

import numpy as np
print(np.__version__)

# Initialize a 3d array -- use the size properties of our image for prtability!
image = np.zeros((dataset.RasterYSize, dataset.RasterXSize, dataset.RasterCount))

# Loop over all bands in dataset
for b in range(dataset.RasterCount):
    # Remember, GDAL index is on 1, but Python is on 0 -- so we add 1 for our GDAL calls
    band = dataset.GetRasterBand(b + 1)
    # Read in the band's data into the third dimension of our array
    image[:, :, b] = band.ReadAsArray()

print(image)

# for imgCol in image:
#     for imgRow in imgCol:
#         if imgRow[0] != 0:
#             print(imgRow)

print(image.dtype)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[19886.]
[21342.]
[21757.]
[23477.]
[25684.]
[27246.]
[27574.]
[28430.]
[28493.]
[28131.]
[28225.]
[27466.]
[26882.]
[26853.]
[25920.]
[25849.]
[26147.]
[26234.]
[26323.]
[25971.]
[25652.]
[26277.]
[26226.]
[26643.]
[28178.]
[27987.]
[26344.]
[24576.]
[22386.]
[20815.]
[19936.]
[20232.]
[19307.]
[17769.]
[16648.]
[15940.]
[15541.]
[15306.]
[15042.]
[14580.]
[14132.]
[13982.]
[14945.]
[19145.]
[19274.]
[19487.]
[21427.]
[20976.]
[20567.]
[20116.]
[19609.]
[18272.]
[17385.]
[17580.]
[18462.]
[18986.]
[17992.]
[16583.]
[16554.]
[14370.]
[15082.]
[17576.]
[17567.]
[17123.]
[17922.]
[19265.]
[20345.]
[21008.]
[20805.]
[20572.]
[20381.]
[20680.]
[21543.]
[22448.]
[23042.]
[23148.]
[23100.]
[22488.]
[22512.]
[23171.]
[22970.]
[20988.]
[20670.]
[21502.]
[21887.]
[21754.]
[22033.]
[21942.]
[22160.]
[22151.]
[22629.]
[23136.]
[22312.]
[22630.]
[22446.]
[21381.]
[20054.]
[20607.]
[19990.]
[20041.]
[19618.]
[19974.]
[19789.]
[20326.]
[20197.]
[20216.]
[21167.]
[

KeyboardInterrupt: 